/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practicotres.Vistas;

import com.mycompany.practicotres.DirectorioTelefonico;
import javax.swing.JOptionPane;

/**
 *
 * @author ezequ
 */
public class BuscarClientesPorCiudad extends javax.swing.JInternalFrame {

    DirectorioTelefonico paginasNaranjas = new DirectorioTelefonico();
    /**
     * Creates new form BuscarClientesPorCiudad
     */
    public BuscarClientesPorCiudad(DirectorioTelefonico paginasNaranjas) {
        initComponents();
        this.paginasNaranjas = paginasNaranjas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JTFbuscarclienteciudad = new javax.swing.JTextField();
        Jdni2 = new javax.swing.JLabel();
        jbotonclienteciudad = new javax.swing.JButton();

        setClosable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Buscar Clientes por Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 24))); // NOI18N

        JTFbuscarclienteciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFbuscarclienteciudadActionPerformed(evt);
            }
        });

        Jdni2.setText("Ciudad");

        jbotonclienteciudad.setText("Buscar");
        jbotonclienteciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonclienteciudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jdni2)
                .addGap(39, 39, 39)
                .addComponent(JTFbuscarclienteciudad)
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jbotonclienteciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFbuscarclienteciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jdni2))
                .addGap(49, 49, 49)
                .addComponent(jbotonclienteciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFbuscarclienteciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFbuscarclienteciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFbuscarclienteciudadActionPerformed

    private void jbotonclienteciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonclienteciudadActionPerformed
        // TODO add your handling code here:

        // buscar clientes por ciudad
        if (paginasNaranjas.buscarClientes(JTFbuscarclienteciudad.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "No viven clientes en esta ciudad\n");
        } else {
            JOptionPane.showMessageDialog(null, "Los clientes que viven en esta ciudad son : \n" + paginasNaranjas.buscarClientes(JTFbuscarclienteciudad.getText()));

        }

    }//GEN-LAST:event_jbotonclienteciudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFbuscarclienteciudad;
    private javax.swing.JLabel Jdni2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbotonclienteciudad;
    // End of variables declaration//GEN-END:variables
}
