/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practicotres.Vistas;

import com.mycompany.practicotres.DirectorioTelefonico;
import javax.swing.JOptionPane;

/**
 *
 * @author ezequ
 */
public class BuscarClientesPorTelefono extends javax.swing.JInternalFrame {

    DirectorioTelefonico paginasNaranjas = new DirectorioTelefonico();
    /**
     * Creates new form BuscarClientesPorTelefono
     */
    public BuscarClientesPorTelefono(DirectorioTelefonico paginasNaranjas) {
        initComponents();
        this.paginasNaranjas = paginasNaranjas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JTFbuscarclientetelefono = new javax.swing.JTextField();
        Jdni3 = new javax.swing.JLabel();
        jbotonbuscarclientetelefono = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Buscar Cliente por Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 24))); // NOI18N

        JTFbuscarclientetelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFbuscarclientetelefonoActionPerformed(evt);
            }
        });

        Jdni3.setText("Telefono");

        jbotonbuscarclientetelefono.setText("Buscar");
        jbotonbuscarclientetelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonbuscarclientetelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Jdni3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(JTFbuscarclientetelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbotonbuscarclientetelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFbuscarclientetelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jdni3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jbotonbuscarclientetelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFbuscarclientetelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFbuscarclientetelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFbuscarclientetelefonoActionPerformed

    private void jbotonbuscarclientetelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonbuscarclientetelefonoActionPerformed
        // TODO add your handling code here:
        // buscar clientes por telefono
        if (paginasNaranjas.buscarCliente(Long.parseLong(JTFbuscarclientetelefono.getText())) == null) {

            JOptionPane.showMessageDialog(null, "No existen clientes con ese telefono\n");
        } else {
            JOptionPane.showMessageDialog(null, "Este es el cliente que contiene este numero de telefono\n" + paginasNaranjas.buscarCliente(Long.parseLong(JTFbuscarclientetelefono.getText())));

        }

    }//GEN-LAST:event_jbotonbuscarclientetelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFbuscarclientetelefono;
    private javax.swing.JLabel Jdni3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbotonbuscarclientetelefono;
    // End of variables declaration//GEN-END:variables
}
