/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicotres.Vistas;

import com.mycompany.practicotres.Cliente;
import com.mycompany.practicotres.DirectorioTelefonico;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class JFMvistaPrincipal extends javax.swing.JFrame {

    DirectorioTelefonico paginasNaranjas = new DirectorioTelefonico();
    

    /**
     * Creates new form JFMvistaPrincipal
     */
    public JFMvistaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        JTFdni1 = new javax.swing.JTextField();
        Jdni1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMGestion = new javax.swing.JMenu();
        jMIFormularioClientes = new javax.swing.JMenuItem();
        jMIBorrar = new javax.swing.JMenuItem();
        jMBuscar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Titulo.setText("Formulario de Clientes");

        JTFdni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdni1ActionPerformed(evt);
            }
        });

        Jdni1.setText("DNI");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabajo practico N3");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMGestion.setText("Gestión");

        jMIFormularioClientes.setText("Formulario Clientes");
        jMIFormularioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioClientesActionPerformed(evt);
            }
        });
        jMGestion.add(jMIFormularioClientes);

        jMIBorrar.setText("Borrar");
        jMIBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBorrarActionPerformed(evt);
            }
        });
        jMGestion.add(jMIBorrar);

        jMenuBar1.add(jMGestion);

        jMBuscar.setText("Buscar");

        jMenuItem1.setText("Clientes por Ciudad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMBuscar.add(jMenuItem1);

        jMenuItem2.setText("Clientes por Telefono");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMBuscar.add(jMenuItem2);

        jMenuItem4.setText("Telefonos por Apellido");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMBuscar.add(jMenuItem4);

        jMenuBar1.add(jMBuscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFdni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdni1ActionPerformed

    private void jMIFormularioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioClientesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioClientes fm = new FormularioClientes(paginasNaranjas);
        fm.setVisible(true);
        escritorio.add(fm);
        escritorio.moveToFront(fm);
    }//GEN-LAST:event_jMIFormularioClientesActionPerformed

    private void jMIBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBorrarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BorrarClientes bc = new BorrarClientes(paginasNaranjas);
        bc.setVisible(true);
        escritorio.add(bc);
        escritorio.moveToFront(bc);
    }//GEN-LAST:event_jMIBorrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarClientesPorCiudad bcc = new BuscarClientesPorCiudad(paginasNaranjas);
        bcc.setVisible(true);
        escritorio.add(bcc);
        escritorio.moveToFront(bcc);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarClientesPorTelefono bct = new BuscarClientesPorTelefono(paginasNaranjas);
        bct.setVisible(true);
        escritorio.add(bct);
        escritorio.moveToFront(bct);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarTelefonosPorApellido bta = new BuscarTelefonosPorApellido(paginasNaranjas);
        bta.setVisible(true);
        escritorio.add(bta);
        escritorio.moveToFront(bta);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMvistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMvistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMvistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMvistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMvistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFdni1;
    private javax.swing.JLabel Jdni1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMBuscar;
    private javax.swing.JMenu jMGestion;
    private javax.swing.JMenuItem jMIBorrar;
    private javax.swing.JMenuItem jMIFormularioClientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
